{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "twitter-as-a-database",
    "description": "Using Twitter as a Database as a hobby project! Tweets can be found at <a href=https://twitter.com/tweets_as_a_db>here</a>.",
    "externalDocs": {
      "description": "GitHub Repository",
      "url": "https://github.com/syall/Twitter-as-a-Database"
    },
    "license": {
      "name": "MIT"
    }
  },
  "servers": [
    {
      "url": "https://twitter-as-a-db.herokuapp.com/",
      "description": "heroku"
    },
    {
      "url": "https://localhost:3000",
      "description": "development"
    }
  ],
  "paths": {
    "/users": {
      "get": {
        "summary": "Returns a list of Public Users or Returns a Specific User",
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "user",
            "schema": {
              "type": "string"
            },
            "required": false,
            "description": "User to Get"
          }
        ],
        "responses": {
          "200": {
            "description": "A List of Public Users or a Single User",
            "content": {
              "application/json": {
                "examples": {
                  "List": {
                    "value": [
                      {
                        "user": "steven",
                        "active": "true"
                      }
                    ]
                  },
                  "Single": {
                    "value": {
                      "user": "steven",
                      "active": "true"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/Public Users"
                }
              }
            }
          },
          "default": {
            "description": "Unexpected error",
            "content": {
              "application/json": {
                "examples": {
                  "List Error": {
                    "value": {
                      "message": "Unable to get Public Users."
                    }
                  },
                  "Single Error": {
                    "value": {
                      "message": "Unable to get Public User."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/users/search": {
      "get": {
        "summary": "Returns a list of Public Users that match the Query",
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "params",
            "schema": {
              "type": "object"
            },
            "style": "form",
            "explode": true,
            "description": "Query for Columns of Public Users",
            "examples": {
              "user s and active false": {
                "value": {
                  "user": "s",
                  "active": false
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A list of Public Users that match the Query",
            "content": {
              "application/json": {
                "examples": {
                  "steven": {
                    "value": [
                      {
                        "user": "steven",
                        "active": "true"
                      }
                    ]
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/Public Users"
                }
              }
            }
          },
          "default": {
            "description": "Unexpected error",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "message": "Unable to get Public Users."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/users/create": {
      "post": {
        "summary": "Returns created Public User",
        "tags": [
          "Users"
        ],
        "requestBody": {
          "description": "Creation Information",
          "required": true,
          "content": {
            "application/json": {
              "examples": {
                "bob": {
                  "value": {
                    "user": {
                      "value": "bob",
                      "type": "strg",
                      "visibility": "public"
                    },
                    "password": {
                      "value": "test",
                      "type": "strg",
                      "visibility": "secret"
                    },
                    "active": {
                      "value": "true",
                      "type": "bool",
                      "visibility": "public"
                    }
                  }
                }
              },
              "schema": {
                "$ref": "#/components/schemas/Creation"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Public User created",
            "content": {
              "application/json": {
                "examples": {
                  "bob": {
                    "value": {
                      "user": "bob",
                      "active": "true"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/Public User"
                }
              }
            }
          },
          "default": {
            "description": "Unexpected error",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "message": "Unable to create user."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/users/update/{user}": {
      "put": {
        "summary": "Returns updated Public User",
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "user",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "User to update"
          }
        ],
        "requestBody": {
          "description": "Update Information",
          "required": true,
          "content": {
            "application/json": {
              "examples": {
                "trust": {
                  "value": {
                    "trust": {
                      "visibility": "public",
                      "value": true,
                      "type": "bool"
                    }
                  }
                }
              },
              "schema": {
                "type": "object"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Public User updated",
            "content": {
              "application/json": {
                "examples": {
                  "steven": {
                    "value": {
                      "user": "steven",
                      "active": "true"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/Public User"
                }
              }
            }
          },
          "default": {
            "description": "Unexpected error",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "message": "Unable to update user."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/users/delete/{user}": {
      "delete": {
        "summary": "Returns deleted Public User",
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "user",
            "schema": {
              "type": "string"
            },
            "required": true,
            "description": "User to delete"
          }
        ],
        "responses": {
          "200": {
            "description": "Public User deleted",
            "content": {
              "application/json": {
                "examples": {
                  "steven": {
                    "value": {
                      "user": "steven",
                      "active": "true"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/Public User"
                }
              }
            }
          },
          "default": {
            "description": "Unexpected error",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "message": "Unable to delete user."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "summary": "Authenticates a User",
        "tags": [
          "Authentication"
        ],
        "requestBody": {
          "description": "Login Information",
          "required": true,
          "content": {
            "application/json": {
              "examples": {
                "steven": {
                  "value": {
                    "username": "steven",
                    "password": "test123"
                  }
                }
              },
              "schema": {
                "$ref": "#/components/schemas/Login"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Authentication Successful!",
            "content": {
              "application/json": {
                "examples": {
                  "steven": {
                    "value": {
                      "message": "Authentication Successful!"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/Login Success"
                }
              }
            }
          },
          "default": {
            "description": "Unexpected error",
            "content": {
              "application/json": {
                "examples": {
                  "User not found": {
                    "value": {
                      "message": "User not found."
                    }
                  },
                  "Password Incorrect": {
                    "value": {
                      "message": "Password Incorrect."
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "required": [
          "username",
          "password"
        ],
        "properties": {
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "Public User": {
        "type": "object",
        "required": [
          "username"
        ],
        "properties": {
          "username": {
            "type": "string"
          }
        }
      },
      "Public Users": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Public User"
        }
      },
      "Login": {
        "type": "object",
        "required": [
          "username",
          "password"
        ],
        "properties": {
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "Login Success": {
        "type": "object",
        "required": [
          "message"
        ],
        "properties": {
          "message": {
            "type": "string"
          }
        }
      },
      "Error": {
        "type": "object",
        "required": [
          "message"
        ],
        "properties": {
          "message": {
            "type": "string"
          }
        }
      },
      "Creation": {
        "type": "object",
        "required": [
          "user",
          "password"
        ],
        "properties": {
          "user": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      }
    }
  }
}
